import type { SessionEntry } from '../types.js';

function outputExtension(entry: SessionEntry): string | null {
  const path =
    typeof entry.result.path === 'string'
      ? entry.result.path
      : typeof entry.result.before === 'string'
        ? entry.result.before
        : null;
  if (!path) return null;
  return path.split('.').pop()?.toLowerCase() ?? null;
}

export function DetailPane({ entry }: { entry: SessionEntry | null }) {
  if (!entry) {
    return (
      <section className="detail">
        <div className="placeholder">Select an op to inspect its output.</div>
      </section>
    );
  }

  const ext = outputExtension(entry);
  const isVideo = ext === 'mp4' || ext === 'mov' || ext === 'webm';
  const isImage = ext === 'jpg' || ext === 'jpeg' || ext === 'png';
  const outputUrl = `/api/output/${entry.id}`;

  return (
    <section className="detail">
      <h2>{entry.tool}</h2>
      <div className="id">
        {entry.id} · {new Date(entry.timestamp).toLocaleString()}
      </div>

      {isVideo ? (
        // biome-ignore lint/a11y/useMediaCaption: caption tracks aren't generated by the editor; local preview only
        <video src={outputUrl} controls />
      ) : isImage ? (
        <img src={outputUrl} alt={`${entry.tool} output`} />
      ) : (
        <div className="no-preview">No previewable output (or result has no playable file).</div>
      )}

      <details>
        <summary>args</summary>
        <pre className="args">{JSON.stringify(entry.args, null, 2)}</pre>
      </details>
      <details>
        <summary>result</summary>
        <pre className="args">{JSON.stringify(entry.result, null, 2)}</pre>
      </details>
    </section>
  );
}
